

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="29" height="29" viewBox="0 0 29 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_35547)">
<path d="M5.07765 23.1101C4.90187 23.4499 5.26515 23.7546 5.5464 23.6023L7.30421 22.6882L6.02687 21.4109L5.07765 23.1101ZM6.56592 20.4148L8.31202 22.1726L9.00342 21.8093L23.2652 7.61793C23.8394 7.04371 23.8394 6.11793 23.2652 5.55543C22.6909 4.98121 21.7769 4.98121 21.2144 5.54371L6.94092 19.7468L6.56592 20.4148Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_35547">
<rect width="18.6643" height="18.6314" fill="currentColor" transform="translate(5.03149 5.01123)"/>
</clipPath>
</defs>
</svg>

`;

export const ApplepencilGen = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  