

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="29" height="29" viewBox="0 0 29 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_36868)">
<path d="M17.9368 26.2055C22.179 26.2055 24.9212 23.475 24.9212 19.2328V13.4555C24.9212 11.85 24.4173 10.5609 23.4212 9.64685L16.0266 2.83826C14.5735 1.51404 13.0383 1.03357 11.2102 1.03357H7.58911C5.47974 1.03357 4.07349 2.46326 4.07349 4.58435V22.6898C4.07349 24.893 5.40943 26.2055 7.62427 26.2055H17.9368Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_36868">
<rect width="20.8477" height="25.1836" fill="currentColor" transform="translate(4.07349 1.03357)"/>
</clipPath>
</defs>
</svg>

`;

export const ButtonAngledtopVerticalRightFill = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  