

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="29" height="29" viewBox="0 0 29 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_37304)">
<path d="M6.73218 24.6426H20.947C23.408 24.6426 24.6267 23.4238 24.6267 21.0097V6.70117C24.6267 4.28711 23.408 3.06836 20.947 3.06836H6.73218C4.28296 3.06836 3.05249 4.27539 3.05249 6.70117V21.0097C3.05249 23.4355 4.28296 24.6426 6.73218 24.6426Z" fill="currentColor" fill-opacity="0.85"/>
<path d="M11.0799 19.8261C10.7049 19.4511 10.7049 18.8652 11.0681 18.5254L16.0369 13.8496L11.0681 9.18554C10.6931 8.83398 10.7049 8.23633 11.0916 7.88476C11.4314 7.54492 11.9939 7.58008 12.3689 7.93164L17.3963 12.6543C18.0877 13.2988 18.0877 14.4121 17.3963 15.0449L12.3689 19.7793C12.0291 20.1074 11.3963 20.1308 11.0799 19.8261Z" fill="currentColor"/>
</g>
<defs>
<clipPath id="clip0_2207_37304">
<rect width="21.5742" height="21.5977" fill="currentColor" transform="translate(3.05249 3.04492)"/>
</clipPath>
</defs>
</svg>

`;

export const ChevronForwardSquareFill = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  