

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="29" height="29" viewBox="0 0 29 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_34352)">
<path d="M3.75781 21.2388L11.7734 25.8559C13.1562 26.6528 14.5039 26.6645 15.9101 25.8559L23.9258 21.2388C25.0156 20.6059 25.6015 19.9848 25.6015 18.2856V9.16849C25.6015 7.51615 25.0039 6.91849 24.0078 6.34427L15.9687 1.70364C14.5156 0.859894 13.1328 0.883332 11.7148 1.70364L3.6875 6.34427C2.67969 6.91849 2.08203 7.51615 2.08203 9.16849V18.2856C2.08203 19.9848 2.67969 20.6059 3.75781 21.2388ZM3.96875 13.7622H23.7148V18.2388C23.7148 18.8833 23.5156 19.1997 22.8711 19.563L15.125 24.0513C14.1992 24.5903 13.4609 24.5786 12.5586 24.0513L4.8125 19.563C4.17969 19.1997 3.96875 18.8833 3.96875 18.2388V13.7622Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_34352">
<rect width="23.5195" height="25.3799" fill="currentColor" transform="translate(2.08203 1.07812)"/>
</clipPath>
</defs>
</svg>

`;

export const HexagonTophalfFilled = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  