

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="30" height="29" viewBox="0 0 30 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_34516)">
<path d="M23.2066 23.4483C26.7457 23.4483 29.5113 20.8584 29.5113 17.6358C29.5113 15.1749 28.0934 13.042 25.8082 12.0811C25.8316 6.85449 22.0699 3.08105 17.277 3.08105C14.1012 3.08105 11.8395 4.78027 10.4332 6.83105C7.55042 5.9873 4.40979 8.17871 4.35119 11.46C1.70275 11.8818 0.050415 14.2491 0.050415 17.1084C0.050415 20.5538 3.06213 23.4483 7.06994 23.4483H23.2066Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_34516">
<rect width="29.4609" height="22.2773" fill="currentColor" transform="translate(0.050415 3.08105)"/>
</clipPath>
</defs>
</svg>

`;

export const IcloudFill = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  