

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="29" height="29" viewBox="0 0 29 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_37208)">
<path d="M4.04199 22.5547C4.04199 25.0039 5.24902 26.2227 7.6748 26.2227H20.1201C22.5459 26.2227 23.7529 25.0039 23.7529 22.5547V4.77735C23.7529 2.33985 22.5459 1.09766 20.1201 1.09766H7.6748C5.24902 1.09766 4.04199 2.33985 4.04199 4.77735V22.5547Z" fill="currentColor" fill-opacity="0.85"/>
<path d="M9.1748 14.6915C8.49511 14.6915 8.01465 14.3399 8.01465 13.6954C8.01465 13.0391 8.47168 12.6641 9.1748 12.6641H18.6436C19.3584 12.6641 19.792 13.0391 19.792 13.6954C19.792 14.3399 19.3232 14.6915 18.6436 14.6915H9.1748Z" fill="currentColor"/>
</g>
<defs>
<clipPath id="clip0_2207_37208">
<rect width="19.7109" height="25.1367" fill="currentColor" transform="translate(4.04199 1.09766)"/>
</clipPath>
</defs>
</svg>

`;

export const MinusRectanglePortraitFill = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  