

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="29" height="29" viewBox="0 0 29 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_33664)">
<path d="M23.9191 14.0527C23.9191 19.1855 20.0988 23.3691 15.1301 23.9316C11.8137 21.9394 9.95044 18.4707 9.95044 14.0527C9.95044 9.63477 11.8254 6.1543 15.1887 4.17383C20.1223 4.74805 23.9191 8.91992 23.9191 14.0527Z" fill="currentColor" fill-opacity="0.85"/>
<path d="M25.923 14.0527C25.923 7.51367 20.5207 2.09961 13.9816 2.09961C7.45435 2.09961 2.01685 7.52539 2.01685 14.0527C2.01685 20.5801 7.44263 26.0058 13.9699 26.0058C20.509 26.0058 25.923 20.5801 25.923 14.0527ZM23.9191 14.0527C23.9191 19.1855 20.0988 23.3691 15.1301 23.9316C11.8137 21.9394 9.95044 18.4707 9.95044 14.0527C9.95044 9.63477 11.8254 6.1543 15.1887 4.17383C20.1223 4.74805 23.9191 8.91992 23.9191 14.0527Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_33664">
<rect width="23.9062" height="23.918" fill="currentColor" transform="translate(2.01685 2.09961)"/>
</clipPath>
</defs>
</svg>

`;

export const MoonphaseWaningCrescentInverse = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  