

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="28" height="29" viewBox="0 0 28 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_33659)">
<path d="M13.9531 24.1191C8.4219 24.1191 3.98049 19.6894 3.99221 14.1582C4.00393 8.62695 8.43361 4.19727 13.9531 4.19727V24.1191Z" fill="currentColor" fill-opacity="0.85"/>
<path d="M13.9531 26.1113C20.4922 26.1113 25.9062 20.6855 25.9062 14.1582C25.9062 7.61914 20.5039 2.20508 13.9531 2.20508C7.4375 2.20508 2 7.61914 2 14.1582C2 20.6855 7.42578 26.1113 13.9531 26.1113ZM13.9531 24.1191C8.42188 24.1191 3.98047 19.6894 3.99219 14.1582C4.00391 8.62695 8.43359 4.19727 13.9531 4.19727V24.1191Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_33659">
<rect width="23.9062" height="24.0117" fill="currentColor" transform="translate(2 2.09961)"/>
</clipPath>
</defs>
</svg>

`;

export const MoonphaseFirstQuarterInverse = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  