

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="29" height="29" viewBox="0 0 29 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_34315)">
<path d="M13.8508 0.102539C7.46411 0.102539 3.04614 5.90332 3.04614 14.1298C3.04614 22.3564 7.46411 28.1572 13.8508 28.1572C20.2375 28.1572 24.632 22.3681 24.632 14.1298C24.632 5.8916 20.2375 0.102539 13.8508 0.102539ZM13.8508 1.98926C19.1125 1.98926 22.7453 7.00488 22.7453 14.1298C22.7453 21.2548 19.1125 26.2705 13.8508 26.2705C8.57739 26.2705 4.93286 21.2431 4.93286 14.1298C4.93286 7.00488 8.57739 1.98926 13.8508 1.98926Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_34315">
<rect width="21.5859" height="28.0664" fill="currentColor" transform="translate(3.04614 0.102539)"/>
</clipPath>
</defs>
</svg>

`;

export const OvalPortrait = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  