

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="28" height="29" viewBox="0 0 28 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_33308)">
<path d="M3.67969 24.6821H23.9531C26.4141 24.6821 27.6328 23.4751 27.6328 21.061V6.74072C27.6328 4.32666 26.4141 3.10791 23.9531 3.10791H3.67969C1.23047 3.10791 0 4.32666 0 6.74072V21.061C0 23.4751 1.23047 24.6821 3.67969 24.6821ZM5.92969 22.9243C6.82031 19.9477 9.98438 17.8149 13.8281 17.8149C17.6602 17.8149 20.8242 19.9477 21.7266 22.9243H5.92969ZM13.8281 15.8462C11.5898 15.8227 9.83203 13.9712 9.82031 11.4634C9.80859 9.10791 11.5898 7.1626 13.8281 7.1626C16.0664 7.1626 17.8359 9.10791 17.8359 11.4634C17.8359 13.9712 16.0664 15.8696 13.8281 15.8462Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_33308">
<rect width="27.6328" height="21.5742" fill="currentColor" transform="translate(0 3.10791)"/>
</clipPath>
</defs>
</svg>

`;

export const PersonCropRectangleFill = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  