

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="29" height="29" viewBox="0 0 29 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_33221)">
<path d="M3.03149 6.604V21.3345C3.03149 23.1743 3.55884 23.8306 4.59008 23.8306C7.61352 23.8306 11.7854 20.0454 11.7854 13.9751C11.7854 7.89307 7.61352 4.10791 4.59008 4.10791C3.55884 4.10791 3.03149 4.76416 3.03149 6.604ZM13.8831 13.9751C13.8831 16.4946 16.1331 18.6626 19.0627 18.6626C21.9456 18.6626 24.0901 16.4829 24.0901 13.9751C24.0901 11.4673 21.8987 9.2876 19.0393 9.2876C16.1331 9.2876 13.8831 11.4673 13.8831 13.9751Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_33221">
<rect width="21.0586" height="19.793" fill="currentColor" transform="translate(3.03149 4.10791)"/>
</clipPath>
</defs>
</svg>

`;

export const PersonFillTurnRight = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  