

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="28" height="29" viewBox="0 0 28 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_36295)">
<path d="M13.9531 26.0284C20.4922 26.0284 25.9062 20.6143 25.9062 14.0752C25.9062 7.54785 20.4805 2.12207 13.9414 2.12207C7.41406 2.12207 2 7.54785 2 14.0752C2 20.6143 7.42578 26.0284 13.9531 26.0284Z" fill="currentColor" fill-opacity="0.85"/>
<path d="M13.7891 14.1573L10.0625 10.4307L12.0078 8.46194C13.1797 7.29007 14.6914 7.26663 15.8281 8.40335C16.9648 9.50491 16.9531 11.0401 15.7695 12.2002L13.7891 14.1573ZM13.0977 14.8721L11.1172 16.8409C9.94532 18.001 8.44532 18.0362 7.3086 16.9229C6.19532 15.7979 6.23048 14.2862 7.40235 13.1143L9.35939 11.1221L13.0977 14.8721ZM21.0078 16.4424H14.4688C14.7031 14.8721 16.0742 13.6299 17.7266 13.6299C19.4023 13.6299 20.7852 14.8721 21.0078 16.4424ZM21.0078 17.4268C20.7852 18.9971 19.4141 20.2393 17.7266 20.2393C16.0625 20.2393 14.7031 18.9971 14.4688 17.4268H21.0078Z" fill="currentColor"/>
</g>
<defs>
<clipPath id="clip0_2207_36295">
<rect width="23.9062" height="23.918" fill="currentColor" transform="translate(2 2.11035)"/>
</clipPath>
</defs>
</svg>

`;

export const PillsCircleFill = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  