

  /*
  * This file was generated by expo-sf-symbols
  *
  * 
  */

import React from "react";
import { SvgXml } from "react-native-svg";

interface IconProps {
  width?: number;
  height?: number;
  color?: string;
  opacity?: number;
}

const iconXml = `
<svg width="28" height="29" viewBox="0 0 28 29" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_2207_34065)">
<path d="M12.8501 3.15771H14.7368V24.732H12.8501V3.15771ZM6.68604 24.732H20.9008C23.3618 24.732 24.5805 23.5132 24.5805 21.0991V6.79053C24.5805 4.37647 23.3618 3.15771 20.9008 3.15771H6.68604C4.23682 3.15771 3.00635 4.36475 3.00635 6.79053V21.0991C3.00635 23.5249 4.23682 24.732 6.68604 24.732Z" fill="currentColor" fill-opacity="0.85"/>
</g>
<defs>
<clipPath id="clip0_2207_34065">
<rect width="21.5742" height="21.5977" fill="currentColor" transform="translate(3.00635 3.13428)"/>
</clipPath>
</defs>
</svg>

`;

export const SquareSplit2x1Fill = (props: IconProps) => {
  return (
    <SvgXml xml={iconXml} width={props.width || 40} height={props.height || 40} color={props.color || "black"} opacity={props.opacity || 1} />
  );
};
  